### ISSUE TITLE
patches to BP doc text, Feb 2018

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#11]
1. Intended audience: grammar in sentence 1
2. p 3: old metacat sentence left in
3. p4 s/seberal/several/
4. p15 "context note" missing the word "note" 
5. p 23: s/APath/XPath/
6. f26 element named fundingSource ? thought it was simply funding. check.
7. p 28: entityName should be unique within package (not entity!)
8. p33 Context note for units. really? it may be easier, but is it a good idea?
9. p 34 time zone has typo: "TZD”
10. p 40 see TO DO note (need example)

there are still some LTER-specific bits mixed into general. see p9, 10, under people

**Comment by gremau** [comment]
Fixed these as best I could, see commit 04345ea6835e72662ab88e091a012bd03f04665a

But also, this doc will be replaced
