### ISSUE TITLE
patches for 3a2-attribs and units

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#12]
- write a history; acknowledge LTER, units group.
- split Attributes and Units into different pages? or maybe in-page anchor.
- put the NIST and SI rules before BP recommendations.
- many wording changes. see mob's paper version.
- links: many now broken, or out of date

**Comment by mobb** [comment]
related to #7

**Comment by gremau** [comment]
Resolving since the new version supersedes at least some of these comments.
