### ISSUE TITLE
suggest a markdown version of this (and future) BPs

### ISSUE THREAD

**Issue by srearl** [EDIorg/data-package-best-practices#13]
Suggest that these BPs be preserved and presented in markdown. This would facilitate viewing directly on GitHub, and has the benefits of plain text. You could still link to docx and/or pdf versions, but markdown would be a more open, functional, and reproducible approach.

**Comment by mobb** [comment]
great idea @srearl ! 
And I tried! https://github.com/EDIorg/dm-best-practices/blob/master/EML-BP-doc/archive/eml_bp_by_element.md

But I could not find a markdown flavor that worked universally - with git, wordpress -- and especially so that XML examples were not butchered (a wordpress feature).  The static PDF was a reasonable planB.
Related to #3, #5

**Comment by srearl** [comment]
Hmm, that is really frustrating. Seems that they [markdown flavors] should be really close - I wonder if markdown extra with Jetpack or something like [this](https://github.com/makotokw/wp-gfm) would solve the problem on the Wordpress side? 

Why is Wordpress a consideration, is that what runs the knb site? 

Anyway, if those two flavors are just different enough, I might suggest that archiving in GH is still the way to go anyway even if they have to be written in a more Wordpress-friendly flavor for optimal/preferable document archiving.

**Comment by twhiteaker** [comment]
View the EML BP markdown file in #19 to see what I came up with. There are still some things to work out if the end goal is a PDF (TOC page numbers, page breaks), but at least it renders nicely on GitHub.  Yay syntax highlighting.

**Comment by mobb** [comment]
see bookdown, this is what the EML documentation uses, although I am not sure if the bookdown output can then go back into github pages. or maybe its one or the other (bookdown for external html, native git md for github.io
here is EML docs (generated from md with bookdown): 
https://eml.ecoinformatics.org/eml-schema.html#the-eml-module-and-resources

here is dataone educational material, github.io pages 
https://dataoneorg.github.io/Education/

and they have moved all the BP-bits into this too. I have talked to Amber about merging material, but not sure it would work; D1 granularity is very different from ours. (most of what we have would map to this step)
https://dataoneorg.github.io/Education/bp_step/describe/

**Comment by gremau** [comment]
Formatting/rendering issues from this far back are being closed since we are in a new platform now.
