### ISSUE TITLE
split up the original BP doc, sections and subsections

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#2]
The EML-specific BPs should be a section with some sub-sections
sub-section background:
history, some LTER stuff

sub-section glossary: 
definitions terms used in EML. not too many, see sections I. (intro), 1.2, few others
suggested: "title", "label", "name", "dataset, "data package" 

sub-section EML BPs by element
already started on this.

The BP doc has other material that is better placed into other major sections (peripherial-EML):
ECC  
spatial data
dataset mgt

**Comment by mobb** [comment]
history has timeline, with links to older docs. see the section "V. Other resources"
also should have the names of the contributors.

**Comment by mobb** [comment]
shelving this until wordpress can play nice with XML.

**Comment by gremau** [comment]
Formatting/rendering issues from this far back are being closed since we are in a new platform now.
