### ISSUE TITLE
use "methods" in xpath, instead of "method"

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#23]
From Suzanne R:
...I’ve had to get into the weeds of the EML specification and EML BP document. When looking at the EML BP v3 document, I see that is uses the XPaths /eml:eml/method/methodStep/protocol/ (pages 7-8). It is explained, on page 22, that both appeared in earlier versions (and now this version too!) and that it has been standardized to <methods>. It seems that method should be plural on pages 7 and 8. (Although in reality, ‘method’ is a better term than ‘methods’. We discussed pluralization a lot in the unit dictionary group).

**Comment by gremau** [comment]
Resolved in new version, see commit 04345ea
