### ISSUE TITLE
mechanism to generate a PDF from a group of pages

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#25]
One of the reasons to keep a PDF of the entire BP doc is so that it can be versioned and archived. One reason the current doc is in word-docx is that PDF export is simple. As we move to markdown, we still may want a PDF for this purpose.  

pandoc can probably do this from markdown. for one page is straightforward; for a group of pages, start here for hints:
http://gbraad.nl/blog/document-generation-using-markdown-and-pandoc.html

**Comment by mobb** [comment]
PDFs from a simple book work, but something is amiss with the EML-BP-doc.tex. you have local copy of tex and log to examine. 

```
! Missing number, treated as zero.
<to be read again> 
                   \protect 
l.379 ...nter}\rule{0.5\linewidth}{\linethickness}
                                                  \end{center} 

Error: Failed to compile EML-BP-doc.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See EML-BP-doc.log for more info
```

It might be related to the warning you've been getting, which seemed non-fatal: `[WARNING] Could not parse YAML metadata at line 901 column 1: :3:0: Unexpected '`' `
have not figured out where that is. but as these markdown files were generated from google docs, it is unlikely they are perfect.

**Comment by mobb** [comment]
It's the horizontal rule before each example.

**Comment by mobb** [comment]
creating a minimally acceptable PDF. however, 
- no citation
- too much white space, particularly the margins

I think all this can be controlled via LaTeX, but so far, I have not sussed out where to put that config info. these may have hints:
https://bookdown.org/yihui/bookdown/latexpdf.html
https://pandoc.org/MANUAL.html#variables-for-latex

**Comment by mobb** [comment]
checked in the script. something odd is happening with the output_filename when I try to copy over the final version to archive. Somehow it gets a hidden space in the variable; see it here:
```
Output created: ../docs/EMLmetadata/EML-BP-doc.pdf
[1] "/Volumes/mob/EDI/Data_Package_Best_Practices_website/git_checkouts/data-package-best-practices/docs/EMLmetadata/EML-BP-doc.pdf"
[1] "saving to output to  six.pdf"
[1] FALSE
```
It works fine if I don't run the bookdown command (and all the script does is copy a file)
 where is my R-expert.

**Comment by gremau** [comment]
This applies to the previous bookdown version and we are now in Quarto. Will add a new issue requesting export formats.
