### ISSUE TITLE
revisit markdown drafts from 2017

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#29]
This doc has some of the V2 text as markdown (converted using pandoc):
 /archive/EML-BP-doc/markdown_testing/eml_bp_2011.markdown

related issues: #13

**Comment by mobb** [comment]
##  Notes on migrating from Word to markdown:
from @twhiteaker, he used:

For compiling to PDF from markdown (tested on Windows):
1. Install Python and then enter this in a command prompt: `pip install grip`
2. In a command prompt, enter `grip your-filename.md`. This runs a local server to display the markdown rendered as HTML.
3. Use Chrome's **Save as PDF** option from the Print menu to save the result to PDF.

**Comment by gremau** [comment]
These docs are still available if you checkout a commit from back in 2019, but I think this issue is more about how to render these old markdown files, which probably isn't necessary any longer.
