### ISSUE TITLE
consider adding a section to EML BP for general TextType info

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#31]
TextType is an option (EML 2.2) for many elements, eg, abstract, methods. TextType in EML is a subset of DocBook. Right now, the only way to  know what the available elements are is to look at the schema documentation, which can be a bit offputting. (V3 of BP talks about content for abstract, methods, etc, but not the structure. TextType is structure.

As of EML 2.2, you also have the option of using markdown as a structure. so as we update for 2.2, we could be make it easier to learn about TextType, and when it might be a better choice than markdown.

**Comment by mobb** [comment]
related to #6

**Comment by mobb** [comment]
this might go alongside the XML attribute group id-system-scope page.

**Comment by gremau** [comment]
Described here: https://prerelease-edi-docs.netlify.app/guide-eml-bp/appendix-b-xml-schemas-and-eml#eml-complex-types-and-the-module-system
