### ISSUE TITLE
define committee processes 

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#42]
Committee will need to define the processes it wants to use  

- [ ] for contributions, e.g., fork-PR? 
- [ ] for moderators 
- [ ] eg, when to generate a PDF, where to link it
- [ ] when to use /doc/files and when to use /archive

**Comment by mobb** [comment]
for PDFs (e.g., EML BP versions):
today's think: the current one goes into doc/files. it has a date (and so does the html bookdown). so you should be able to tell by comparing dates if the PDF and HTML might be out of sync.
When a new PDF is generated (e.g. EML BP v4), it goes into then /doc/files and v3 goes into the archive.
It may get confusing to have a static PDF at all. We should ask the IMC what they want to cite: a static PDF or a website with a date? 
Note: ADC (via NCEAS) gives DOIs to their manuals: https://nceas.github.io/datateam-training/training/index.html

**Comment by gremau** [comment]
Closing this after moving content to #35 which is quite similar.
