### ISSUE TITLE
each creator is one party

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#49]
do not put a list of individual names here.

**Comment by twhiteaker** [comment]
I was just about to add this issue.  Good job Margaret from 10 days ago who must have been from the future.

**Comment by gremau** [comment]
I believe this is [well-covered in the v4 version](https://prerelease-edi-docs.netlify.app/guide-eml-bp/chapter-04-people-and-organizations-responsibleparty) of the EML BP doc now.
