### ISSUE TITLE
ideas and notes from LTER non-tabular working group

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#51]
The group noticed the significant overlap between different sections, and thought about ways to reorganize them. no conclusions yet. Possible changes to organization include

Three major sections:

1. EML metadata
2. Raw Data package design
  2.1. Genomics data
  2.2. Image data
  2.3. Model in/output
  2.4. Code/scripts/software as data
  2.5. Non-tabular geospatial data
  2.6. Video
3. General recommendation for all (most) datasets
  3.1. Dates
  3.2. Geographic coordinates: lats/long decimals (projection)
  3.3. Taxa

Other considerations:

- Harmonized/derived data product design
  - climDB
  - ecocomDP
- Distinction between datasets used for synthesis efforts (e.g., EcoComDP, ClimHydro DB), where format of the data is important, vs. regular datasets
- Citation use case: a web link that lasts 6 years. Eg, the duration of an LTER site grant, so a reviewer can see that you did what you said you were going to do.
- Some of the recommendations in (community_surveys) apply to other types of data too. They should be generalized.

Consider a Letter or brief item to Ecological Bulletin when we have something ready.

Also see notes in this groups google drive.

**Comment by gremau** [comment]
Closing this since it is mostly notes that have been incorporated into the current set of guides.
