### ISSUE TITLE
userid example is wrong

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#56]
See: 
https://ediorg.github.io/data-package-best-practices/EMLmetadata/people-and-organizations-parties.html

The attribute on the userid element is `directory`, not `system` 

 ```
 <userId system="https://orcid.org">
      https://orcid.org/0000-0000-0000-0000
   </userId>
```

**Comment by gremau** [comment]
This was fixed in the v3 and v4 (brand-new in 2024) version of the EML BP doc. See 59c1bdc
