### ISSUE TITLE
Data package design sidebar menu

### ISSUE THREAD

**Issue by scelmendorf** [EDIorg/data-package-best-practices#63]
When you open the link https://ediorg.github.io/data-package-best-practices/datapackage-design/ the sidebar shows 'Data in Other Repositories' and 'Very Large Datasets' under Best Practice Recommendations for Data product design, and then also under (7) and (6) in the menu below (6 is now labeled large datasets instead of very large). It is a confusing navigation menu though I understand it because I know the index has short descriptions and the chapters more, it isn't immediately obvious which one I should click on on the sidebar. I am wondering if perhaps instead of duplicating the headings of chapters in the index we should instead just list the other chapters in a table or something at the end of the index?

**Comment by mobb** [comment]
keep in mind that the navigation of a book is generated by the chapter titles. You can put a general description in the book's index page, but the synchronization to the navigation menu will have to be manual. See the bookdown docs for more info.

**Comment by gremau** [comment]
I think this is a stale issue since we've moved to a new system and navigation is improved (I hope - revive this issue if not!)
