### ISSUE TITLE
misdirected link

### ISSUE THREAD

**Issue by rfbrown** [EDIorg/data-package-best-practices#66]
In the table of contents of the bookdown version of the BPs, the side-bar link for "Still Images",  "Chapter 4.2 Recommendations for data packages" links to "Key-Value Pair Tables" "Chapter 1.2 Recommendations for data packages."

**Comment by gremau** [comment]
I _think_ this has been resolved. I may not be seeing what is being referenced here though given that the structure of these docs has changed quite a bit since 2020. Feel free to reopen.
